### ISSUE TITLE
Can't install via alcatraz

### ISSUE THREAD

**Issue by JeremieDaigle** [orta/Snapshots-Peek#2]
Myself and many coworkers have not been able to install this plugin.It just starts installing and then cancels and the bar goes back... is anyone else experiencing this? I really want this to work!

![snapshots plugin](https://cloud.githubusercontent.com/assets/2071211/15073460/83856b9c-1367-11e6-81dc-973f0aa77745.gif)

Ive also tried installing and uninstalling all plugins, even downloading the source code and installing manually, nothing seems to work.

**Comment by orta** [comment]
Interesting, what does `Console.app` say when you do this?

**Comment by orta** [comment]
Fixed via https://github.com/orta/Snapshots-Peek/commit/07b8569c5cd60857271fd174e3f8e9df279d8de1
